# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Widget3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(880, 720)
        Form.setStyleSheet("QWidget#Form {\n"
"    background-image: url(:/resources/resources/Wallpaper3.png);\n"
"}")
        self.close_button = QtWidgets.QPushButton(Form)
        self.close_button.setGeometry(QtCore.QRect(830, 0, 50, 40))
        self.close_button.setStyleSheet("QPushButton {\n"
"    border-image: url(:/resources/resources/Close.png);\n"
"}\n"
"QPushButton::hover {\n"
"    border-image: url(:/resources/resources/Close_hovered.png);\n"
"}")
        self.close_button.setText("")
        self.close_button.setObjectName("close_button")
        self.help_button = QtWidgets.QPushButton(Form)
        self.help_button.setGeometry(QtCore.QRect(780, 0, 50, 40))
        self.help_button.setStyleSheet("QPushButton {\n"
"    border-image: url(:/resources/resources/Help.png);\n"
"}\n"
"QPushButton::hover {\n"
"    border-image: url(:/resources/resources/Help_hovered.png);\n"
"}")
        self.help_button.setText("")
        self.help_button.setObjectName("help_button")
        self.minimize_button = QtWidgets.QPushButton(Form)
        self.minimize_button.setGeometry(QtCore.QRect(730, 0, 50, 40))
        self.minimize_button.setStyleSheet("QPushButton {\n"
"    border-image: url(:/resources/resources/Minimize.png);\n"
"}\n"
"QPushButton::hover {\n"
"    border-image: url(:/resources/resources/Minimize_hovered.png);\n"
"}")
        self.minimize_button.setText("")
        self.minimize_button.setObjectName("minimize_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
import Widget_Resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
